SET(SOURCES components/ui_comp_button.c
    components/ui_comp_card.c
    components/ui_comp_cardbg.c
    components/ui_comp_percent.c
    components/ui_comp.c
    screens/ui_Home.c
    screens/ui_Step1.c
    screens/ui_Step2.c
    screens/ui_Connect.c
    screens/ui_Welcome.c
    screens/ui_Charging.c
    screens/ui_Pricing.c
    screens/ui_Help.c
    screens/ui_End.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    images/ui_img_bg1_png.c
    images/ui_img_left_side_png.c
    images/ui_img_pricing_png.c
    images/ui_img_help_png.c
    images/ui_img_contact_png.c
    images/ui_img_anim1_car_anim_01_png.c
    images/ui_img_bg2_png.c
    images/ui_img_anim2_plug_anim_01_png.c
    images/ui_img_light_png.c
    images/ui_img_bg4_png.c
    images/ui_img_qr_code1_png.c
    images/ui_img_phone_png.c
    images/ui_img_bg3_png.c
    images/ui_img_time_png.c
    images/ui_img_ok_png.c
    images/ui_img_slider_bg2_png.c
    images/ui_img_slider_bg3_png.c
    images/ui_img_slider_bg1_png.c
    images/ui_img_slider_mask2_png.c
    images/ui_img_slider_mask1_png.c
    images/ui_img_pos_png.c
    images/ui_img_qr_code2_png.c
    images/ui_img_anim1_car_anim_02_png.c
    images/ui_img_anim1_car_anim_03_png.c
    images/ui_img_anim1_car_anim_04_png.c
    images/ui_img_anim1_car_anim_05_png.c
    images/ui_img_anim1_car_anim_06_png.c
    images/ui_img_anim1_car_anim_07_png.c
    images/ui_img_anim1_car_anim_08_png.c
    images/ui_img_anim1_car_anim_09_png.c
    images/ui_img_anim1_car_anim_10_png.c
    images/ui_img_anim1_car_anim_11_png.c
    images/ui_img_anim1_car_anim_12_png.c
    images/ui_img_anim1_car_anim_13_png.c
    images/ui_img_anim1_car_anim_14_png.c
    images/ui_img_anim1_car_anim_15_png.c
    images/ui_img_anim1_car_anim_16_png.c
    images/ui_img_anim1_car_anim_17_png.c
    images/ui_img_anim1_car_anim_18_png.c
    images/ui_img_anim1_car_anim_19_png.c
    images/ui_img_anim1_car_anim_20_png.c
    images/ui_img_anim1_car_anim_21_png.c
    images/ui_img_anim2_plug_anim_02_png.c
    images/ui_img_anim2_plug_anim_03_png.c
    images/ui_img_anim2_plug_anim_04_png.c
    images/ui_img_anim2_plug_anim_05_png.c
    images/ui_img_anim2_plug_anim_06_png.c
    images/ui_img_anim2_plug_anim_07_png.c
    images/ui_img_anim2_plug_anim_08_png.c
    images/ui_img_anim2_plug_anim_09_png.c
    images/ui_img_anim2_plug_anim_10_png.c
    images/ui_img_anim2_plug_anim_11_png.c
    images/ui_img_anim2_plug_anim_12_png.c
    images/ui_img_anim2_plug_anim_13_png.c
    images/ui_img_anim2_plug_anim_14_png.c
    images/ui_img_anim2_plug_anim_15_png.c
    fonts/ui_font_Bold.c
    fonts/ui_font_H1.c
    fonts/ui_font_H2.c
    fonts/ui_font_Light.c
    fonts/ui_font_Number.c)

add_library(ui ${SOURCES})
