// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef _EV_CHARGER_UI_H
#define _EV_CHARGER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"
#include "screens/ui_Step1.h"
#include "screens/ui_Step2.h"
#include "screens/ui_Connect.h"
#include "screens/ui_Welcome.h"
#include "screens/ui_Charging.h"
#include "screens/ui_Pricing.h"
#include "screens/ui_Help.h"
#include "screens/ui_End.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * charging1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * charging2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * charging3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * left_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * left_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bottom_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bottom_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * phone_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * big_left_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ready_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ready_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * end_bar_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * end_bar_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * car1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * plug_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * light_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_left_side_png);    // assets/left_side.png
LV_IMG_DECLARE(ui_img_pricing_png);    // assets/pricing.png
LV_IMG_DECLARE(ui_img_help_png);    // assets/help.png
LV_IMG_DECLARE(ui_img_contact_png);    // assets/contact.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_01_png);    // assets/anim1/car_anim_01.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_01_png);    // assets/anim2/plug_anim_01.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png
LV_IMG_DECLARE(ui_img_bg4_png);    // assets/bg4.png
LV_IMG_DECLARE(ui_img_qr_code1_png);    // assets/qr_code1.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png
LV_IMG_DECLARE(ui_img_slider_bg2_png);    // assets/slider_bg2.png
LV_IMG_DECLARE(ui_img_slider_bg3_png);    // assets/slider_bg3.png
LV_IMG_DECLARE(ui_img_slider_bg1_png);    // assets/slider_bg1.png
LV_IMG_DECLARE(ui_img_slider_mask2_png);    // assets/slider_mask2.png
LV_IMG_DECLARE(ui_img_slider_mask1_png);    // assets/slider_mask1.png
LV_IMG_DECLARE(ui_img_pos_png);    // assets/pos.png
LV_IMG_DECLARE(ui_img_qr_code2_png);    // assets/qr_code2.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_02_png);    // assets/anim1/car_anim_02.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_03_png);    // assets/anim1/car_anim_03.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_04_png);    // assets/anim1/car_anim_04.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_05_png);    // assets/anim1/car_anim_05.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_06_png);    // assets/anim1/car_anim_06.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_07_png);    // assets/anim1/car_anim_07.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_08_png);    // assets/anim1/car_anim_08.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_09_png);    // assets/anim1/car_anim_09.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_10_png);    // assets/anim1/car_anim_10.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_11_png);    // assets/anim1/car_anim_11.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_12_png);    // assets/anim1/car_anim_12.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_13_png);    // assets/anim1/car_anim_13.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_14_png);    // assets/anim1/car_anim_14.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_15_png);    // assets/anim1/car_anim_15.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_16_png);    // assets/anim1/car_anim_16.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_17_png);    // assets/anim1/car_anim_17.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_18_png);    // assets/anim1/car_anim_18.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_19_png);    // assets/anim1/car_anim_19.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_20_png);    // assets/anim1/car_anim_20.png
LV_IMG_DECLARE(ui_img_anim1_car_anim_21_png);    // assets/anim1/car_anim_21.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_02_png);    // assets/anim2/plug_anim_02.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_03_png);    // assets/anim2/plug_anim_03.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_04_png);    // assets/anim2/plug_anim_04.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_05_png);    // assets/anim2/plug_anim_05.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_06_png);    // assets/anim2/plug_anim_06.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_07_png);    // assets/anim2/plug_anim_07.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_08_png);    // assets/anim2/plug_anim_08.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_09_png);    // assets/anim2/plug_anim_09.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_10_png);    // assets/anim2/plug_anim_10.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_11_png);    // assets/anim2/plug_anim_11.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_12_png);    // assets/anim2/plug_anim_12.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_13_png);    // assets/anim2/plug_anim_13.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_14_png);    // assets/anim2/plug_anim_14.png
LV_IMG_DECLARE(ui_img_anim2_plug_anim_15_png);    // assets/anim2/plug_anim_15.png

// FONTS
LV_FONT_DECLARE(ui_font_Bold);
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_H2);
LV_FONT_DECLARE(ui_font_Light);
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
