// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

void ui_comp_button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_card_create_hook(lv_obj_t * comp)
{
}

void ui_comp_cardbg_create_hook(lv_obj_t * comp)
{
}

void ui_comp_percent_create_hook(lv_obj_t * comp)
{
}
