// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef _UI_COMP_CARDBG_H
#define _UI_COMP_CARDBG_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cardbg
#define UI_COMP_CARDBG_CARDBG 0
#define _UI_COMP_CARDBG_NUM 1
lv_obj_t * ui_cardbg_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
