// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef _UI_COMP_PERCENT_H
#define _UI_COMP_PERCENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT percent
#define UI_COMP_PERCENT_PERCENT 0
#define UI_COMP_PERCENT_PERCENT_GROUP 1
#define UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL 2
#define UI_COMP_PERCENT_CORNER 3
#define _UI_COMP_PERCENT_NUM 4
lv_obj_t * ui_percent_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
