// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef _UI_COMP_BUTTON_H
#define _UI_COMP_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT button
#define UI_COMP_BUTTON_BUTTON 0
#define UI_COMP_BUTTON_BUTTON_LABEL 1
#define _UI_COMP_BUTTON_NUM 2
lv_obj_t * ui_button_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
