// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef _UI_COMP_CARD_H
#define _UI_COMP_CARD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT card
#define UI_COMP_CARD_CARD 0
#define UI_COMP_CARD_CARDBG2 1
#define UI_COMP_CARD_CARDBG2_CARD_H 2
#define UI_COMP_CARD_CARDBG2_CARD_TEXT 3
#define UI_COMP_CARD_CARDBG2_CARD_TITLE 4
#define _UI_COMP_CARD_NUM 5
lv_obj_t * ui_card_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
