// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Connect = NULL;
lv_obj_t * ui_card4 = NULL;
lv_obj_t * ui_spinner = NULL;
lv_obj_t * ui_auth_test1 = NULL;
// event funtions
void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_card4, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_card4, 0);
    }
}

void ui_event_card4_cardbg2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Welcome, LV_SCR_LOAD_ANIM_FADE_ON, 0, 200, &ui_Welcome_screen_init);
    }
}

// build funtions

void ui_Connect_screen_init(void)
{
    ui_Connect = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Connect, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_card4 = ui_card_create(ui_Connect);
    lv_obj_set_width(ui_card4, 680);
    lv_obj_set_height(ui_card4, 363);
    lv_obj_set_x(ui_card4, 0);
    lv_obj_set_y(ui_card4, 0);

    lv_obj_set_width(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2), 623);
    lv_obj_set_height(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2), 285);

    lv_obj_set_x(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_H), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_H), 90);
    lv_label_set_text(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_H), "Connecting\nto vehicle");
    lv_obj_set_style_text_letter_space(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_H), 0,
                                       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_H), -10,
                                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_flag(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_TEXT), LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_label_set_text(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Please wait...");

    ui_spinner = lv_spinner_create(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2));
    //lv_spinner_set_anim_params(ui_spinner, 1000, 90);
    lv_obj_set_width(ui_spinner, 180);
    lv_obj_set_height(ui_spinner, 180);
    lv_obj_set_x(ui_spinner, -30);
    lv_obj_set_y(ui_spinner, 0);
    lv_obj_set_align(ui_spinner, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_spinner, &ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_spinner, lv_color_hex(0x3D3C50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_spinner, lv_color_hex(0x1F8BFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spinner, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_spinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_spinner, 3);
    ui_auth_test1 = lv_label_create(ui_Connect);
    lv_obj_set_width(ui_auth_test1, 555);
    lv_obj_set_height(ui_auth_test1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auth_test1, 0);
    lv_obj_set_y(ui_auth_test1, -25);
    lv_obj_set_align(ui_auth_test1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_auth_test1,
                      "If the connection with the vehicle is failed, the process will be terminated automatically.");
    lv_obj_set_style_text_color(ui_auth_test1, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_auth_test1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_auth_test1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_auth_test1, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_card4, UI_COMP_CARD_CARDBG2), ui_event_card4_cardbg2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Connect, ui_event_Connect, LV_EVENT_ALL, NULL);

}

void ui_Connect_screen_destroy(void)
{
    if(ui_Connect) lv_obj_del(ui_Connect);

    // NULL screen variables
    ui_Connect = NULL;
    ui_card4 = NULL;
    ui_spinner = NULL;
    ui_auth_test1 = NULL;

}
