// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_CHARGING_H
#define UI_CHARGING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Charging
extern void ui_Charging_screen_init(void);
extern void ui_Charging_screen_destroy(void);
extern void ui_event_Charging(lv_event_t * e);
extern lv_obj_t * ui_Charging;
extern lv_obj_t * ui_content_group5;
extern lv_obj_t * ui_content5;
extern lv_obj_t * ui_info_group5;
extern lv_obj_t * ui_contact_icon5;
extern lv_obj_t * ui_call_number5;
extern lv_obj_t * ui_date5;
extern void ui_event_button5_button(lv_event_t * e);
extern lv_obj_t * ui_button5;
extern lv_obj_t * ui_charging_time_group;
extern lv_obj_t * ui_charging_tme;
extern lv_obj_t * ui_Label1_charging;
extern lv_obj_t * ui_group1;
extern lv_obj_t * ui_Label3_charging;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_charging_cost_group;
extern lv_obj_t * ui_charging_cost;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_group2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_charging_energie_group;
extern lv_obj_t * ui_charging_energie;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_group3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_charging_speed_group;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_group4;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_charge_bar_group;
extern lv_obj_t * ui_cardbg3;
extern lv_obj_t * ui_anim_bg2;
extern lv_obj_t * ui_anim_bg3;
extern lv_obj_t * ui_anim_bg1;
extern lv_obj_t * ui_mask1;
extern lv_obj_t * ui_mask2;
extern lv_obj_t * ui_charge_bar;
extern lv_obj_t * ui_start_bar;
extern lv_obj_t * ui_start_bar_indicator;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_charge_bar_indicator;
extern lv_obj_t * ui_percent_number1;
extern lv_obj_t * ui_percent_number2;
extern lv_obj_t * ui_percent1;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

