// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_CONNECT_H
#define UI_CONNECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connect
extern void ui_Connect_screen_init(void);
extern void ui_Connect_screen_destroy(void);
extern void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_card4;
extern void ui_event_card4_cardbg2(lv_event_t * e);
extern lv_obj_t * ui_spinner;
extern lv_obj_t * ui_auth_test1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

