// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_END_H
#define UI_END_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_End
extern void ui_End_screen_init(void);
extern void ui_End_screen_destroy(void);
extern void ui_event_End(lv_event_t * e);
extern lv_obj_t * ui_End;
extern lv_obj_t * ui_content_group6;
extern lv_obj_t * ui_content6;
extern lv_obj_t * ui_info_group6;
extern lv_obj_t * ui_contact_icon6;
extern lv_obj_t * ui_call_number6;
extern lv_obj_t * ui_date6;
extern void ui_event_button6_button(lv_event_t * e);
extern lv_obj_t * ui_button6;
extern lv_obj_t * ui_cardbg4;
extern lv_obj_t * ui_fee_group48;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_fee_group37;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_summary_price;
extern lv_obj_t * ui_summary_price1;
extern lv_obj_t * ui_charge_bar_group1;
extern lv_obj_t * ui_cardbg1;
extern lv_obj_t * ui_charge_bar1;
extern lv_obj_t * ui_start_bar1;
extern lv_obj_t * ui_start_bar_indicator1;
extern lv_obj_t * ui_start_bar3;
extern lv_obj_t * ui_charge_bar_indicator1;
extern lv_obj_t * ui_percent4;
extern lv_obj_t * ui_start_bar2;
extern lv_obj_t * ui_start_bar_indicator2;
extern lv_obj_t * ui_percent3;
extern lv_obj_t * ui_Chart_group;
extern lv_obj_t * ui_chart_scrollbar;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

