// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_End = NULL;
lv_obj_t * ui_content_group6 = NULL;
lv_obj_t * ui_content6 = NULL;
lv_obj_t * ui_info_group6 = NULL;
lv_obj_t * ui_contact_icon6 = NULL;
lv_obj_t * ui_call_number6 = NULL;
lv_obj_t * ui_date6 = NULL;
lv_obj_t * ui_button6 = NULL;
lv_obj_t * ui_cardbg4 = NULL;
lv_obj_t * ui_fee_group48 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_fee_group37 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_summary_price = NULL;
lv_obj_t * ui_summary_price1 = NULL;
lv_obj_t * ui_charge_bar_group1 = NULL;
lv_obj_t * ui_cardbg1 = NULL;
lv_obj_t * ui_charge_bar1 = NULL;
lv_obj_t * ui_start_bar1 = NULL;
lv_obj_t * ui_start_bar_indicator1 = NULL;
lv_obj_t * ui_start_bar3 = NULL;
lv_obj_t * ui_charge_bar_indicator1 = NULL;
lv_obj_t * ui_percent4 = NULL;
lv_obj_t * ui_start_bar2 = NULL;
lv_obj_t * ui_start_bar_indicator2 = NULL;
lv_obj_t * ui_percent3 = NULL;
lv_obj_t * ui_Chart_group = NULL;
lv_obj_t * ui_chart_scrollbar = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Chart2_Xaxis = NULL;
lv_obj_t * ui_Chart2_Yaxis1 = NULL;
lv_obj_t * ui_Chart2_Yaxis2 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
// event funtions
void ui_event_End(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_button6, 0);
        top_on_Animation(ui_Chart_group, 0);
        top_on_Animation(ui_cardbg4, 100);
        end_bar_on_Animation(ui_charge_bar_group1, 100);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_button6, 0);
        top_off_Animation(ui_Chart_group, 0);
        top_off_Animation(ui_cardbg4, 100);
        end_bar_off_Animation(ui_charge_bar_group1, 100);
    }
}

void ui_event_button6_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}

// build funtions

void ui_End_screen_init(void)
{
    ui_End = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_End, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_End, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group6 = lv_obj_create(ui_End);
    lv_obj_set_width(ui_content_group6, lv_pct(100));
    lv_obj_set_height(ui_content_group6, lv_pct(100));
    lv_obj_set_align(ui_content_group6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content6 = lv_obj_create(ui_content_group6);
    lv_obj_set_height(ui_content6, lv_pct(100));
    lv_obj_set_flex_grow(ui_content6, 1);
    lv_obj_set_align(ui_content6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_content6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group6 = lv_obj_create(ui_content6);
    lv_obj_set_width(ui_info_group6, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_info_group6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_info_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon6 = lv_image_create(ui_info_group6);
    lv_image_set_src(ui_contact_icon6, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_contact_icon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number6 = lv_label_create(ui_info_group6);
    lv_obj_set_width(ui_call_number6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number6, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_call_number6, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number6, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date6 = lv_label_create(ui_content6);
    lv_obj_set_width(ui_date6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date6, 0);
    lv_obj_set_y(ui_date6, 1);
    lv_obj_set_align(ui_date6, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date6, "Jan. 06. 2026. 14:49");
    lv_obj_set_style_text_color(ui_date6, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date6, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button6 = ui_button_create(ui_content6);
    lv_obj_set_x(ui_button6, 0);
    lv_obj_set_y(ui_button6, 0);
    lv_obj_set_align(ui_button6, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_bg_color(ui_button6, lv_color_hex(0x01D358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_button6, lv_color_hex(0x01D358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button6, lv_color_hex(0x00B74B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button6, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_label_set_text(ui_comp_get_child(ui_button6, UI_COMP_BUTTON_BUTTON_LABEL), "Finish");

    ui_cardbg4 = ui_cardbg_create(ui_content6);
    lv_obj_set_width(ui_cardbg4, 436);
    lv_obj_set_height(ui_cardbg4, 245);
    lv_obj_set_x(ui_cardbg4, 0);
    lv_obj_set_y(ui_cardbg4, 45);
    lv_obj_set_align(ui_cardbg4, LV_ALIGN_TOP_RIGHT);

    ui_fee_group48 = lv_obj_create(ui_cardbg4);
    lv_obj_set_width(ui_fee_group48, 345);
    lv_obj_set_height(ui_fee_group48, 97);
    lv_obj_set_x(ui_fee_group48, 0);
    lv_obj_set_y(ui_fee_group48, 18);
    lv_obj_set_align(ui_fee_group48, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_fee_group48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_fee_group48);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label18, "Charging time");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_fee_group48);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label19, "53 min");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group48, 0);
    ui_fee_group37 = lv_obj_create(ui_cardbg4);
    lv_obj_set_width(ui_fee_group37, 345);
    lv_obj_set_height(ui_fee_group37, 97);
    lv_obj_remove_flag(ui_fee_group37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_fee_group37);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label15, "Total energy delivered");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_fee_group37);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label17, "87 kWh");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group37, 1);
    ui_summary_price = lv_label_create(ui_content6);
    lv_obj_set_width(ui_summary_price, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_summary_price, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_summary_price, 0);
    lv_obj_set_y(ui_summary_price, 142);
    lv_obj_set_align(ui_summary_price, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_summary_price, "$118");
    lv_obj_set_style_text_color(ui_summary_price, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_summary_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_summary_price, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_summary_price1 = lv_label_create(ui_content6);
    lv_obj_set_width(ui_summary_price1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_summary_price1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_summary_price1, -10);
    lv_obj_set_y(ui_summary_price1, 64);
    lv_obj_set_align(ui_summary_price1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_summary_price1, "Total session cost");
    lv_obj_set_style_text_color(ui_summary_price1, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_summary_price1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_summary_price1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge_bar_group1 = lv_obj_create(ui_content6);
    lv_obj_set_height(ui_charge_bar_group1, 144);
    lv_obj_set_width(ui_charge_bar_group1, lv_pct(79));
    lv_obj_set_x(ui_charge_bar_group1, -27);
    lv_obj_set_y(ui_charge_bar_group1, 28);
    lv_obj_set_align(ui_charge_bar_group1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_charge_bar_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge_bar_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_charge_bar_group1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cardbg1 = ui_cardbg_create(ui_charge_bar_group1);
    lv_obj_set_height(ui_cardbg1, 44);
    lv_obj_set_width(ui_cardbg1, lv_pct(95));
    lv_obj_set_x(ui_cardbg1, 1);
    lv_obj_set_y(ui_cardbg1, 66);
    lv_obj_set_align(ui_cardbg1, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_radius(ui_cardbg1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_cardbg1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge_bar1 = lv_obj_create(ui_charge_bar_group1);
    lv_obj_set_height(ui_charge_bar1, 124);
    lv_obj_set_width(ui_charge_bar1, lv_pct(95));
    lv_obj_set_flex_flow(ui_charge_bar1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_charge_bar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_charge_bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge_bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar1 = lv_obj_create(ui_charge_bar1);
    lv_obj_set_width(ui_start_bar1, 105);
    lv_obj_set_height(ui_start_bar1, LV_SIZE_CONTENT);    /// 255
    lv_obj_set_align(ui_start_bar1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_start_bar1, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_start_bar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_start_bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar_indicator1 = lv_obj_create(ui_start_bar1);
    lv_obj_set_height(ui_start_bar_indicator1, 35);
    lv_obj_set_width(ui_start_bar_indicator1, lv_pct(100));
    lv_obj_remove_flag(ui_start_bar_indicator1, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_start_bar_indicator1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_start_bar_indicator1, lv_color_hex(0x00B94C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_start_bar_indicator1, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_start_bar_indicator1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_start_bar_indicator1, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_start_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_start_bar_indicator1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar3 = lv_obj_create(ui_charge_bar1);
    lv_obj_set_width(ui_start_bar3, lv_pct(62));
    lv_obj_set_height(ui_start_bar3, LV_SIZE_CONTENT);    /// 255
    lv_obj_set_align(ui_start_bar3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_start_bar3, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_start_bar3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_start_bar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge_bar_indicator1 = lv_obj_create(ui_start_bar3);
    lv_obj_set_height(ui_charge_bar_indicator1, 35);
    lv_obj_set_width(ui_charge_bar_indicator1, lv_pct(62));
    lv_obj_set_x(ui_charge_bar_indicator1, -355);
    lv_obj_set_y(ui_charge_bar_indicator1, 12);
    lv_obj_set_align(ui_charge_bar_indicator1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_charge_bar_indicator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_charge_bar_indicator1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_charge_bar_indicator1, lv_color_hex(0x0067D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_charge_bar_indicator1, lv_color_hex(0x3FBDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_charge_bar_indicator1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_charge_bar_indicator1, lv_color_hex(0x3FCFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_charge_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_charge_bar_indicator1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent4 = ui_percent_create(ui_start_bar3);
    lv_obj_set_x(ui_percent4, 0);
    lv_obj_set_y(ui_percent4, 0);

    lv_label_set_text(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), "Start 15%");

    lv_obj_set_align(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_CORNER), LV_ALIGN_BOTTOM_LEFT);

    ui_start_bar2 = lv_obj_create(ui_charge_bar1);
    lv_obj_set_height(ui_start_bar2, LV_SIZE_CONTENT);    /// 255
    lv_obj_set_flex_grow(ui_start_bar2, 1);
    lv_obj_set_align(ui_start_bar2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_start_bar2, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_start_bar2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_start_bar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar_indicator2 = lv_obj_create(ui_start_bar2);
    lv_obj_set_height(ui_start_bar_indicator2, 35);
    lv_obj_set_width(ui_start_bar_indicator2, lv_pct(61));
    lv_obj_set_align(ui_start_bar_indicator2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_start_bar_indicator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar_indicator2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar_indicator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent3 = ui_percent_create(ui_start_bar2);
    lv_obj_set_x(ui_percent3, 0);
    lv_obj_set_y(ui_percent3, 0);

    lv_label_set_text(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), "End 80%");

    lv_obj_set_align(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_CORNER), LV_ALIGN_BOTTOM_LEFT);

    ui_Chart_group = lv_obj_create(ui_End);
    lv_obj_set_width(ui_Chart_group, 521);
    lv_obj_set_height(ui_Chart_group, 379);
    lv_obj_set_x(ui_Chart_group, 0);
    lv_obj_set_y(ui_Chart_group, 47);
    lv_obj_remove_flag(ui_Chart_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Chart_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chart_scrollbar = lv_obj_create(ui_Chart_group);
    lv_obj_set_width(ui_chart_scrollbar, lv_pct(100));
    lv_obj_set_height(ui_chart_scrollbar, lv_pct(100));
    lv_obj_set_x(ui_chart_scrollbar, 23);
    lv_obj_set_y(ui_chart_scrollbar, -23);
    lv_obj_set_align(ui_chart_scrollbar, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_radius(ui_chart_scrollbar, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chart_scrollbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_scrollbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chart_scrollbar, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chart_scrollbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chart_scrollbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chart_scrollbar, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_chart_scrollbar, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_scrollbar, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chart_scrollbar, 50, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chart_scrollbar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chart_scrollbar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chart_scrollbar, 35, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_chart_scrollbar);
    lv_obj_set_width(ui_Chart2, lv_pct(200));
    lv_obj_set_height(ui_Chart2, lv_pct(85));
    lv_obj_set_align(ui_Chart2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_Chart2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart2, 22);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 1, 100);
    lv_chart_set_div_line_count(ui_Chart2, 10, 22);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Chart2, lv_color_hex(0x100F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Chart2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart2, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart2, lv_color_hex(0x22223D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Chart2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Chart2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Chart2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2_Xaxis = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart2_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart2_Xaxis, 0, 22 > 0 ? 22 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart2_Xaxis, (22 > 0 ? 22 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Xaxis, 1 >= 1 ? 1 : 1);
    ui_Chart2_Yaxis1 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart2_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart2_Yaxis1,  1, 100);
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis1, (11 > 0 ? 11 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart2_Yaxis2 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Chart2_Yaxis2, false);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x3BB7FC),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 3, 12, 20, 28, 36, 44, 48, 52, 57, 60, 64, 68, 70, 72, 75, 78, 80, 81, 82, 83, 84, 85 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart2, true, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Chart2, 4, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart2, true, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Chart2, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Chart2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Chart2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_Chart2, 10, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart2_Xaxis, lv_color_hex(0x100F1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2_Xaxis, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2_Yaxis1, lv_color_hex(0x100F1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2_Yaxis1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2_Yaxis2, lv_color_hex(0x100F1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2_Yaxis2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2_Xaxis, lv_color_hex(0x100F1F), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2_Xaxis, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2_Yaxis1, lv_color_hex(0x100F1F), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2_Yaxis1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2_Yaxis2, lv_color_hex(0x100F1F), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2_Yaxis2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2_Xaxis, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2_Xaxis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2_Yaxis1, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2_Yaxis1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2_Yaxis2, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2_Yaxis2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart2, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Label21 = lv_label_create(ui_Chart_group);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 60);
    lv_obj_set_y(ui_Label21, 0);
    lv_obj_set_align(ui_Label21, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label21, "Time (min)");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Chart_group);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 100);
    lv_obj_set_y(ui_Label22, 56);
    lv_label_set_text(ui_Label22, "Total energy delivered (kWh)");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button6, ui_event_button6_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_End, ui_event_End, LV_EVENT_ALL, NULL);

}

void ui_End_screen_destroy(void)
{
    if(ui_End) lv_obj_del(ui_End);

    // NULL screen variables
    ui_End = NULL;
    ui_content_group6 = NULL;
    ui_content6 = NULL;
    ui_info_group6 = NULL;
    ui_contact_icon6 = NULL;
    ui_call_number6 = NULL;
    ui_date6 = NULL;
    ui_button6 = NULL;
    ui_cardbg4 = NULL;
    ui_fee_group48 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_fee_group37 = NULL;
    ui_Label15 = NULL;
    ui_Label17 = NULL;
    ui_summary_price = NULL;
    ui_summary_price1 = NULL;
    ui_charge_bar_group1 = NULL;
    ui_cardbg1 = NULL;
    ui_charge_bar1 = NULL;
    ui_start_bar1 = NULL;
    ui_start_bar_indicator1 = NULL;
    ui_start_bar3 = NULL;
    ui_charge_bar_indicator1 = NULL;
    ui_percent4 = NULL;
    ui_start_bar2 = NULL;
    ui_start_bar_indicator2 = NULL;
    ui_percent3 = NULL;
    ui_Chart_group = NULL;
    ui_chart_scrollbar = NULL;
    ui_Chart2 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;

}
