// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Help = NULL;
lv_obj_t * ui_content_group8 = NULL;
lv_obj_t * ui_content8 = NULL;
lv_obj_t * ui_info_group8 = NULL;
lv_obj_t * ui_contact_icon8 = NULL;
lv_obj_t * ui_call_number8 = NULL;
lv_obj_t * ui_date8 = NULL;
lv_obj_t * ui_button8 = NULL;
lv_obj_t * ui_card6 = NULL;
lv_obj_t * ui_welcom_text85 = NULL;
lv_obj_t * ui_SLS = NULL;
lv_obj_t * ui_welcom_text86 = NULL;
lv_obj_t * ui_qr2 = NULL;
// event funtions
void ui_event_Help(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_button8, 0);
        big_left_on_Animation(ui_card6, 0);
        ready_on_Animation(ui_qr2, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_button8, 0);
        left_off_Animation(ui_card6, 0);
        ready_off_Animation(ui_qr2, 0);
    }
}

void ui_event_button8_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Help_screen_init(void)
{
    ui_Help = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Help, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Help, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group8 = lv_obj_create(ui_Help);
    lv_obj_set_width(ui_content_group8, lv_pct(100));
    lv_obj_set_height(ui_content_group8, lv_pct(100));
    lv_obj_set_align(ui_content_group8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_group8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content8 = lv_obj_create(ui_content_group8);
    lv_obj_set_height(ui_content8, lv_pct(100));
    lv_obj_set_flex_grow(ui_content8, 1);
    lv_obj_set_align(ui_content8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_content8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group8 = lv_obj_create(ui_content8);
    lv_obj_set_width(ui_info_group8, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_info_group8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_info_group8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon8 = lv_image_create(ui_info_group8);
    lv_image_set_src(ui_contact_icon8, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_contact_icon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number8 = lv_label_create(ui_info_group8);
    lv_obj_set_width(ui_call_number8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number8, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_call_number8, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number8, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date8 = lv_label_create(ui_content8);
    lv_obj_set_width(ui_date8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date8, 0);
    lv_obj_set_y(ui_date8, 1);
    lv_obj_set_align(ui_date8, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date8, "Jan. 06. 2026. 14:49");
    lv_obj_set_style_text_color(ui_date8, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date8, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button8 = ui_button_create(ui_content8);
    lv_obj_set_x(ui_button8, 0);
    lv_obj_set_y(ui_button8, 0);
    lv_obj_set_align(ui_button8, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button8, UI_COMP_BUTTON_BUTTON_LABEL), "Back");

    ui_card6 = ui_card_create(ui_Help);
    lv_obj_set_width(ui_card6, 706);
    lv_obj_set_height(ui_card6, 600);
    lv_obj_set_x(ui_card6, 0);
    lv_obj_set_y(ui_card6, 0);
    lv_obj_set_align(ui_card6, LV_ALIGN_LEFT_MID);

    lv_obj_set_width(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2), 650);
    lv_obj_set_height(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2), 514);
    lv_obj_set_x(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2), 20);
    lv_obj_set_style_shadow_width(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_H), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_H), 99);
    lv_label_set_text(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_H), "Authentication");
    lv_obj_add_flag(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_H), LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_welcom_text85 = lv_label_create(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_welcom_text85, lv_pct(100));
    lv_obj_set_height(ui_welcom_text85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_welcom_text85, 0);
    lv_obj_set_y(ui_welcom_text85, -169);
    lv_obj_set_align(ui_welcom_text85, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_welcom_text85, "Powered by LVGL");
    lv_obj_add_flag(ui_welcom_text85, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_welcom_text85, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_welcom_text85, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_welcom_text85, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_welcom_text85, 1);
    lv_obj_set_x(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_TEXT), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_TEXT), 177);
    lv_label_set_text(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "Next generation UI editor for individuals and professionals to design and develop beautiful UIs for your embedded devices quickly and easily.\n\nSquareLine Studio offers flexible licenses for all use cases,including personal use, startups, and large companies as well.");

    lv_obj_set_x(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_label_set_text(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2_CARD_TITLE), "This demo created by");

    ui_SLS = lv_label_create(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_SLS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLS, 0);
    lv_obj_set_y(ui_SLS, 69);
    lv_label_set_text(ui_SLS, "SquareLine Studio");
    lv_obj_set_style_text_color(ui_SLS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLS, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_SLS, 4);
    ui_welcom_text86 = lv_label_create(ui_comp_get_child(ui_card6, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_welcom_text86, lv_pct(100));
    lv_obj_set_height(ui_welcom_text86, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_welcom_text86, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_welcom_text86,
                      "Under the hood SquareLine Studio uses the amazing LVGL GUI library. LVGL is the most popular free and open-source embedded graphics library to create beautiful UIs for any MCU, MPU and display type.");
    lv_obj_set_style_text_color(ui_welcom_text86, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_welcom_text86, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_welcom_text86, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_welcom_text86, 5);
    ui_qr2 = lv_image_create(ui_Help);
    lv_image_set_src(ui_qr2, &ui_img_qr_code2_png);
    lv_obj_set_width(ui_qr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_qr2, 286);
    lv_obj_set_y(ui_qr2, 36);
    lv_obj_set_align(ui_qr2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qr2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_qr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_button8, ui_event_button8_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Help, ui_event_Help, LV_EVENT_ALL, NULL);

}

void ui_Help_screen_destroy(void)
{
    if(ui_Help) lv_obj_del(ui_Help);

    // NULL screen variables
    ui_Help = NULL;
    ui_content_group8 = NULL;
    ui_content8 = NULL;
    ui_info_group8 = NULL;
    ui_contact_icon8 = NULL;
    ui_call_number8 = NULL;
    ui_date8 = NULL;
    ui_button8 = NULL;
    ui_card6 = NULL;
    ui_welcom_text85 = NULL;
    ui_SLS = NULL;
    ui_welcom_text86 = NULL;
    ui_qr2 = NULL;

}
