// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_content_group1;
extern lv_obj_t * ui_slidebar1;
extern void ui_event_icon_group1(lv_event_t * e);
extern lv_obj_t * ui_icon_group1;
extern lv_obj_t * ui_pricing_icon1;
extern lv_obj_t * ui_pricing_label1;
extern void ui_event_icon_group2(lv_event_t * e);
extern lv_obj_t * ui_icon_group2;
extern lv_obj_t * ui_help_icon1;
extern lv_obj_t * ui_help_label1;
extern lv_obj_t * ui_content1;
extern lv_obj_t * ui_info_group1;
extern lv_obj_t * ui_contact_icon1;
extern lv_obj_t * ui_call_number1;
extern lv_obj_t * ui_date1;
extern lv_obj_t * ui_charger_id;
extern lv_obj_t * ui_card;
extern lv_obj_t * ui_s1_car;
extern lv_obj_t * ui_button_group;
extern void ui_event_button1_button(lv_event_t * e);
extern lv_obj_t * ui_button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

