// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_content_group1 = NULL;
lv_obj_t * ui_slidebar1 = NULL;
lv_obj_t * ui_icon_group1 = NULL;
lv_obj_t * ui_pricing_icon1 = NULL;
lv_obj_t * ui_pricing_label1 = NULL;
lv_obj_t * ui_icon_group2 = NULL;
lv_obj_t * ui_help_icon1 = NULL;
lv_obj_t * ui_help_label1 = NULL;
lv_obj_t * ui_content1 = NULL;
lv_obj_t * ui_info_group1 = NULL;
lv_obj_t * ui_contact_icon1 = NULL;
lv_obj_t * ui_call_number1 = NULL;
lv_obj_t * ui_date1 = NULL;
lv_obj_t * ui_charger_id = NULL;
lv_obj_t * ui_card = NULL;
lv_obj_t * ui_s1_car = NULL;
lv_obj_t * ui_button_group = NULL;
lv_obj_t * ui_button1 = NULL;
// event funtions
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        left_on_Animation(ui_card, 0);
        bottom_on_Animation(ui_button1, 0);
        car1_Animation(ui_s1_car, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_card, 0);
        bottom_off_Animation(ui_button1, 0);
    }
}

void ui_event_icon_group1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pricing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Pricing_screen_init);
    }
}

void ui_event_icon_group2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Help, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Help_screen_init);
    }
}

void ui_event_button1_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Step1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Step1_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Home, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group1 = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_content_group1, lv_pct(100));
    lv_obj_set_height(ui_content_group1, lv_pct(100));
    lv_obj_set_align(ui_content_group1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slidebar1 = lv_obj_create(ui_content_group1);
    lv_obj_set_width(ui_slidebar1, 97);
    lv_obj_set_height(ui_slidebar1, lv_pct(100));
    lv_obj_set_align(ui_slidebar1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_slidebar1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_slidebar1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_slidebar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_slidebar1, &ui_img_left_side_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_slidebar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_slidebar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_slidebar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_slidebar1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_slidebar1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_slidebar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group1 = lv_obj_create(ui_slidebar1);
    lv_obj_set_width(ui_icon_group1, 75);
    lv_obj_set_height(ui_icon_group1, 75);
    lv_obj_set_align(ui_icon_group1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_icon_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_icon_group1, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_icon_group1, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_icon_group1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_pricing_icon1 = lv_image_create(ui_icon_group1);
    lv_image_set_src(ui_pricing_icon1, &ui_img_pricing_png);
    lv_obj_set_width(ui_pricing_icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pricing_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pricing_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_pricing_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pricing_label1 = lv_label_create(ui_icon_group1);
    lv_obj_set_width(ui_pricing_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pricing_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pricing_label1, "Pricing");
    lv_obj_set_style_text_color(ui_pricing_label1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pricing_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pricing_label1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group2 = lv_obj_create(ui_slidebar1);
    lv_obj_set_width(ui_icon_group2, 75);
    lv_obj_set_height(ui_icon_group2, 75);
    lv_obj_set_align(ui_icon_group2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_icon_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_icon_group2, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_icon_group2, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_icon_group2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_help_icon1 = lv_image_create(ui_icon_group2);
    lv_image_set_src(ui_help_icon1, &ui_img_help_png);
    lv_obj_set_width(ui_help_icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_help_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_help_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_help_label1 = lv_label_create(ui_icon_group2);
    lv_obj_set_width(ui_help_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_help_label1, "Help");
    lv_obj_set_style_text_color(ui_help_label1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_help_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_help_label1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content1 = lv_obj_create(ui_content_group1);
    lv_obj_set_height(ui_content1, lv_pct(100));
    lv_obj_set_flex_grow(ui_content1, 1);
    lv_obj_set_align(ui_content1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_content1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content1, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content1, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content1, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content1, 22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group1 = lv_obj_create(ui_content1);
    lv_obj_set_width(ui_info_group1, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_info_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_info_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon1 = lv_image_create(ui_info_group1);
    lv_image_set_src(ui_contact_icon1, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_contact_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number1 = lv_label_create(ui_info_group1);
    lv_obj_set_width(ui_call_number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number1, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_call_number1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date1 = lv_label_create(ui_content1);
    lv_obj_set_width(ui_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date1, 0);
    lv_obj_set_y(ui_date1, 1);
    lv_obj_set_align(ui_date1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date1, "Jan. 06. 2026. 14:49");
    lv_obj_set_style_text_color(ui_date1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date1, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charger_id = lv_label_create(ui_content1);
    lv_obj_set_width(ui_charger_id, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_charger_id, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_charger_id, 0);
    lv_obj_set_y(ui_charger_id, -7);
    lv_obj_set_align(ui_charger_id, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_charger_id, "Charger #5879965-08");
    lv_obj_set_style_text_color(ui_charger_id, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_charger_id, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_charger_id, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_card = ui_card_create(ui_Home);
    lv_obj_set_x(ui_card, -202);
    lv_obj_set_y(ui_card, -97);

    lv_label_set_text(ui_comp_get_child(ui_card, UI_COMP_CARD_CARDBG2_CARD_H), "Get started!");

    lv_label_set_text(ui_comp_get_child(ui_card, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "The world's fastest and best charger is at your disposal.");

    lv_label_set_text(ui_comp_get_child(ui_card, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Welcome!");

    ui_s1_car = lv_image_create(ui_Home);
    lv_image_set_src(ui_s1_car, &ui_img_anim1_car_anim_01_png);
    lv_obj_set_width(ui_s1_car, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_s1_car, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_s1_car, 100);
    lv_obj_set_y(ui_s1_car, 75);
    lv_obj_set_align(ui_s1_car, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1_car, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_s1_car, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button_group = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_button_group, lv_pct(100));
    lv_obj_set_height(ui_button_group, lv_pct(100));
    lv_obj_set_x(ui_button_group, 1);
    lv_obj_set_y(ui_button_group, 0);
    lv_obj_set_align(ui_button_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_button_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_button_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_button_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_button_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_button_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_button_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button1 = ui_button_create(ui_button_group);
    lv_obj_set_x(ui_button1, 0);
    lv_obj_set_y(ui_button1, 0);
    lv_obj_set_align(ui_button1, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button1, UI_COMP_BUTTON_BUTTON_LABEL), "Start Charging");

    lv_obj_add_event_cb(ui_icon_group1, ui_event_icon_group1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_icon_group2, ui_event_icon_group2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button1, ui_event_button1_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_content_group1 = NULL;
    ui_slidebar1 = NULL;
    ui_icon_group1 = NULL;
    ui_pricing_icon1 = NULL;
    ui_pricing_label1 = NULL;
    ui_icon_group2 = NULL;
    ui_help_icon1 = NULL;
    ui_help_label1 = NULL;
    ui_content1 = NULL;
    ui_info_group1 = NULL;
    ui_contact_icon1 = NULL;
    ui_call_number1 = NULL;
    ui_date1 = NULL;
    ui_charger_id = NULL;
    ui_card = NULL;
    ui_s1_car = NULL;
    ui_button_group = NULL;
    ui_button1 = NULL;

}
