// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_HELP_H
#define UI_HELP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Help
extern void ui_Help_screen_init(void);
extern void ui_Help_screen_destroy(void);
extern void ui_event_Help(lv_event_t * e);
extern lv_obj_t * ui_Help;
extern lv_obj_t * ui_content_group8;
extern lv_obj_t * ui_content8;
extern lv_obj_t * ui_info_group8;
extern lv_obj_t * ui_contact_icon8;
extern lv_obj_t * ui_call_number8;
extern lv_obj_t * ui_date8;
extern void ui_event_button8_button(lv_event_t * e);
extern lv_obj_t * ui_button8;
extern lv_obj_t * ui_card6;
extern lv_obj_t * ui_welcom_text85;
extern lv_obj_t * ui_SLS;
extern lv_obj_t * ui_welcom_text86;
extern lv_obj_t * ui_qr2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

