// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_PRICING_H
#define UI_PRICING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Pricing
extern void ui_Pricing_screen_init(void);
extern void ui_Pricing_screen_destroy(void);
extern void ui_event_Pricing(lv_event_t * e);
extern lv_obj_t * ui_Pricing;
extern lv_obj_t * ui_content_group7;
extern lv_obj_t * ui_content7;
extern lv_obj_t * ui_info_group7;
extern lv_obj_t * ui_contact_icon7;
extern lv_obj_t * ui_call_number7;
extern lv_obj_t * ui_date7;
extern void ui_event_button7_button(lv_event_t * e);
extern lv_obj_t * ui_button7;
extern lv_obj_t * ui_card5;
extern lv_obj_t * ui_welcom_text84;
extern lv_obj_t * ui_fee_group19;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_fee_group24;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_pos;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

