// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Pricing = NULL;
lv_obj_t * ui_content_group7 = NULL;
lv_obj_t * ui_content7 = NULL;
lv_obj_t * ui_info_group7 = NULL;
lv_obj_t * ui_contact_icon7 = NULL;
lv_obj_t * ui_call_number7 = NULL;
lv_obj_t * ui_date7 = NULL;
lv_obj_t * ui_button7 = NULL;
lv_obj_t * ui_card5 = NULL;
lv_obj_t * ui_welcom_text84 = NULL;
lv_obj_t * ui_fee_group19 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_fee_group24 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_pos = NULL;
// event funtions
void ui_event_Pricing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_button7, 0);
        big_left_on_Animation(ui_card5, 0);
        ready_on_Animation(ui_pos, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_button7, 0);
        ready_off_Animation(ui_pos, 0);
        left_off_Animation(ui_card5, 0);
    }
}

void ui_event_button7_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Pricing_screen_init(void)
{
    ui_Pricing = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Pricing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Pricing, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group7 = lv_obj_create(ui_Pricing);
    lv_obj_set_width(ui_content_group7, lv_pct(100));
    lv_obj_set_height(ui_content_group7, lv_pct(100));
    lv_obj_set_align(ui_content_group7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_group7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content7 = lv_obj_create(ui_content_group7);
    lv_obj_set_height(ui_content7, lv_pct(100));
    lv_obj_set_flex_grow(ui_content7, 1);
    lv_obj_set_align(ui_content7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_content7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group7 = lv_obj_create(ui_content7);
    lv_obj_set_width(ui_info_group7, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_info_group7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_info_group7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon7 = lv_image_create(ui_info_group7);
    lv_image_set_src(ui_contact_icon7, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_contact_icon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number7 = lv_label_create(ui_info_group7);
    lv_obj_set_width(ui_call_number7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number7, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_call_number7, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number7, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date7 = lv_label_create(ui_content7);
    lv_obj_set_width(ui_date7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date7, 0);
    lv_obj_set_y(ui_date7, 1);
    lv_obj_set_align(ui_date7, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date7, "Jan. 06. 2026. 14:49");
    lv_obj_set_style_text_color(ui_date7, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date7, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button7 = ui_button_create(ui_content7);
    lv_obj_set_x(ui_button7, 0);
    lv_obj_set_y(ui_button7, 0);
    lv_obj_set_align(ui_button7, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button7, UI_COMP_BUTTON_BUTTON_LABEL), "Back");

    ui_card5 = ui_card_create(ui_Pricing);
    lv_obj_set_width(ui_card5, 706);
    lv_obj_set_height(ui_card5, 600);
    lv_obj_set_x(ui_card5, 0);
    lv_obj_set_y(ui_card5, 0);
    lv_obj_set_align(ui_card5, LV_ALIGN_LEFT_MID);

    lv_obj_set_width(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2), 650);
    lv_obj_set_height(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2), 514);
    lv_obj_set_x(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2), 25);
    lv_obj_set_style_shadow_width(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_H), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_H), 99);
    lv_label_set_text(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_H), "Authentication");
    lv_obj_add_flag(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_H), LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_x(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_TEXT), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_TEXT), 72);
    lv_label_set_text(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "The first 30 minutes of fast charging are free.\nAfter 60 minutes you get 10% discount.");

    lv_obj_set_x(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_label_set_text(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Pricing");

    ui_welcom_text84 = lv_label_create(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_welcom_text84, lv_pct(100));
    lv_obj_set_height(ui_welcom_text84, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_welcom_text84, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_welcom_text84, "The charging speed depends on the type of car\nand the capacity of the network.");
    lv_obj_set_style_text_color(ui_welcom_text84, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_welcom_text84, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_welcom_text84, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_welcom_text84, 3);
    ui_fee_group19 = lv_obj_create(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_fee_group19, 460);
    lv_obj_set_height(ui_fee_group19, 130);
    lv_obj_set_x(ui_fee_group19, 0);
    lv_obj_set_y(ui_fee_group19, -50);
    lv_obj_set_align(ui_fee_group19, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_fee_group19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_fee_group19);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 28);
    lv_label_set_text(ui_Label1, "Session fee");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_fee_group19);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label3, "$0.00");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group19, 4);
    ui_fee_group24 = lv_obj_create(ui_comp_get_child(ui_card5, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_fee_group24, 460);
    lv_obj_set_height(ui_fee_group24, 130);
    lv_obj_set_x(ui_fee_group24, 0);
    lv_obj_set_y(ui_fee_group24, 130);
    lv_obj_set_align(ui_fee_group24, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_fee_group24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_fee_group24);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label4, "1-250 kW");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_fee_group24);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label5, "$0.21/kWh");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group24, 5);
    ui_pos = lv_image_create(ui_Pricing);
    lv_image_set_src(ui_pos, &ui_img_pos_png);
    lv_obj_set_width(ui_pos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pos, 282);
    lv_obj_set_y(ui_pos, 3);
    lv_obj_set_align(ui_pos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_pos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_button7, ui_event_button7_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pricing, ui_event_Pricing, LV_EVENT_ALL, NULL);

}

void ui_Pricing_screen_destroy(void)
{
    if(ui_Pricing) lv_obj_del(ui_Pricing);

    // NULL screen variables
    ui_Pricing = NULL;
    ui_content_group7 = NULL;
    ui_content7 = NULL;
    ui_info_group7 = NULL;
    ui_contact_icon7 = NULL;
    ui_call_number7 = NULL;
    ui_date7 = NULL;
    ui_button7 = NULL;
    ui_card5 = NULL;
    ui_welcom_text84 = NULL;
    ui_fee_group19 = NULL;
    ui_Label1 = NULL;
    ui_Label3 = NULL;
    ui_fee_group24 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_pos = NULL;

}
