// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_STEP1_H
#define UI_STEP1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Step1
extern void ui_Step1_screen_init(void);
extern void ui_Step1_screen_destroy(void);
extern void ui_event_Step1(lv_event_t * e);
extern lv_obj_t * ui_Step1;
extern lv_obj_t * ui_plug_anim;
extern lv_obj_t * ui_light;
extern lv_obj_t * ui_content_group2;
extern lv_obj_t * ui_slidebar2;
extern void ui_event_icon_group3(lv_event_t * e);
extern lv_obj_t * ui_icon_group3;
extern lv_obj_t * ui_pricing_icon2;
extern lv_obj_t * ui_pricing_label2;
extern void ui_event_icon_group4(lv_event_t * e);
extern lv_obj_t * ui_icon_group4;
extern lv_obj_t * ui_help_icon2;
extern lv_obj_t * ui_help_label2;
extern lv_obj_t * ui_content2;
extern lv_obj_t * ui_info_group2;
extern lv_obj_t * ui_contact_icon2;
extern lv_obj_t * ui_call_number2;
extern lv_obj_t * ui_date3;
extern void ui_event_button2_button(lv_event_t * e);
extern lv_obj_t * ui_button2;
extern lv_obj_t * ui_step_count1;
extern lv_obj_t * ui_step_count2;
extern lv_obj_t * ui_card1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

