// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_STEP2_H
#define UI_STEP2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Step2
extern void ui_Step2_screen_init(void);
extern void ui_Step2_screen_destroy(void);
extern void ui_event_Step2(lv_event_t * e);
extern lv_obj_t * ui_Step2;
extern lv_obj_t * ui_content_group3;
extern lv_obj_t * ui_slidebar3;
extern void ui_event_icon_group5(lv_event_t * e);
extern lv_obj_t * ui_icon_group5;
extern lv_obj_t * ui_pricing_icon3;
extern lv_obj_t * ui_pricing_label3;
extern void ui_event_icon_group6(lv_event_t * e);
extern lv_obj_t * ui_icon_group6;
extern lv_obj_t * ui_help_icon3;
extern lv_obj_t * ui_help_label3;
extern lv_obj_t * ui_content3;
extern lv_obj_t * ui_info_group3;
extern lv_obj_t * ui_contact_icon3;
extern lv_obj_t * ui_call_number3;
extern lv_obj_t * ui_date2;
extern void ui_event_button3_button(lv_event_t * e);
extern lv_obj_t * ui_button3;
extern lv_obj_t * ui_step_count3;
extern lv_obj_t * ui_step_count4;
extern lv_obj_t * ui_auth_test;
extern lv_obj_t * ui_qr1;
extern lv_obj_t * ui_card2;
extern lv_obj_t * ui_step_label2;
extern lv_obj_t * ui_phone;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

