// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Step2 = NULL;
lv_obj_t * ui_content_group3 = NULL;
lv_obj_t * ui_slidebar3 = NULL;
lv_obj_t * ui_icon_group5 = NULL;
lv_obj_t * ui_pricing_icon3 = NULL;
lv_obj_t * ui_pricing_label3 = NULL;
lv_obj_t * ui_icon_group6 = NULL;
lv_obj_t * ui_help_icon3 = NULL;
lv_obj_t * ui_help_label3 = NULL;
lv_obj_t * ui_content3 = NULL;
lv_obj_t * ui_info_group3 = NULL;
lv_obj_t * ui_contact_icon3 = NULL;
lv_obj_t * ui_call_number3 = NULL;
lv_obj_t * ui_date2 = NULL;
lv_obj_t * ui_button3 = NULL;
lv_obj_t * ui_step_count3 = NULL;
lv_obj_t * ui_step_count4 = NULL;
lv_obj_t * ui_auth_test = NULL;
lv_obj_t * ui_qr1 = NULL;
lv_obj_t * ui_card2 = NULL;
lv_obj_t * ui_step_label2 = NULL;
lv_obj_t * ui_phone = NULL;
// event funtions
void ui_event_Step2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_button3, 0);
        left_on_Animation(ui_card2, 0);
        phone_Animation(ui_phone, 0);
        top_on_Animation(ui_qr1, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_card2, 0);
        bottom_off_Animation(ui_button3, 0);
        bottom_off_Animation(ui_phone, 100);
        top_off_Animation(ui_qr1, 0);
    }
}

void ui_event_icon_group5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Pricing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Pricing_screen_init);
    }
}

void ui_event_icon_group6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Help, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Help_screen_init);
    }
}

void ui_event_button3_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Connect_screen_init);
    }
}

// build funtions

void ui_Step2_screen_init(void)
{
    ui_Step2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Step2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Step2, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group3 = lv_obj_create(ui_Step2);
    lv_obj_set_width(ui_content_group3, lv_pct(100));
    lv_obj_set_height(ui_content_group3, lv_pct(100));
    lv_obj_set_align(ui_content_group3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slidebar3 = lv_obj_create(ui_content_group3);
    lv_obj_set_width(ui_slidebar3, 97);
    lv_obj_set_height(ui_slidebar3, lv_pct(100));
    lv_obj_set_align(ui_slidebar3, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_slidebar3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_slidebar3, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_slidebar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_slidebar3, &ui_img_left_side_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_slidebar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_slidebar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_slidebar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_slidebar3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_slidebar3, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_slidebar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group5 = lv_obj_create(ui_slidebar3);
    lv_obj_set_width(ui_icon_group5, 75);
    lv_obj_set_height(ui_icon_group5, 75);
    lv_obj_set_align(ui_icon_group5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_icon_group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pricing_icon3 = lv_image_create(ui_icon_group5);
    lv_image_set_src(ui_pricing_icon3, &ui_img_pricing_png);
    lv_obj_set_width(ui_pricing_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pricing_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pricing_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_pricing_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pricing_label3 = lv_label_create(ui_icon_group5);
    lv_obj_set_width(ui_pricing_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pricing_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pricing_label3, "Pricing");
    lv_obj_set_style_text_color(ui_pricing_label3, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pricing_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pricing_label3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group6 = lv_obj_create(ui_slidebar3);
    lv_obj_set_width(ui_icon_group6, 75);
    lv_obj_set_height(ui_icon_group6, 75);
    lv_obj_set_align(ui_icon_group6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_icon_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_help_icon3 = lv_image_create(ui_icon_group6);
    lv_image_set_src(ui_help_icon3, &ui_img_help_png);
    lv_obj_set_width(ui_help_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_help_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_help_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_help_label3 = lv_label_create(ui_icon_group6);
    lv_obj_set_width(ui_help_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_help_label3, "Help");
    lv_obj_set_style_text_color(ui_help_label3, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_help_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_help_label3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content3 = lv_obj_create(ui_content_group3);
    lv_obj_set_height(ui_content3, lv_pct(100));
    lv_obj_set_flex_grow(ui_content3, 1);
    lv_obj_set_align(ui_content3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_content3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content3, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content3, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content3, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content3, 22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group3 = lv_obj_create(ui_content3);
    lv_obj_set_width(ui_info_group3, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_info_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_info_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon3 = lv_image_create(ui_info_group3);
    lv_image_set_src(ui_contact_icon3, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_contact_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number3 = lv_label_create(ui_info_group3);
    lv_obj_set_width(ui_call_number3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number3, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_call_number3, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number3, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date2 = lv_label_create(ui_content3);
    lv_obj_set_width(ui_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date2, 0);
    lv_obj_set_y(ui_date2, 1);
    lv_obj_set_align(ui_date2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date2, "Jan. 06. 2026. 14:49");
    lv_obj_set_style_text_color(ui_date2, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date2, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button3 = ui_button_create(ui_content3);
    lv_obj_set_x(ui_button3, -8);
    lv_obj_set_y(ui_button3, 0);
    lv_obj_set_align(ui_button3, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button3, UI_COMP_BUTTON_BUTTON_LABEL), "Next Step");

    ui_step_count3 = lv_label_create(ui_content3);
    lv_obj_set_width(ui_step_count3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_step_count3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_step_count3, -249);
    lv_obj_set_y(ui_step_count3, 0);
    lv_obj_set_align(ui_step_count3, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_step_count3, "/2");
    lv_obj_set_style_text_color(ui_step_count3, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_step_count3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_step_count3, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_step_count4 = lv_label_create(ui_content3);
    lv_obj_set_width(ui_step_count4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_step_count4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_step_count4, -300);
    lv_obj_set_y(ui_step_count4, 0);
    lv_obj_set_align(ui_step_count4, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_step_count4, "2");
    lv_obj_set_style_text_color(ui_step_count4, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_step_count4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_step_count4, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auth_test = lv_label_create(ui_content3);
    lv_obj_set_width(ui_auth_test, 402);
    lv_obj_set_height(ui_auth_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auth_test, -8);
    lv_obj_set_y(ui_auth_test, -89);
    lv_obj_set_align(ui_auth_test, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_auth_test,
                      "Please start your EV Charger application and scan this QR code to authenticate your device and set the payment method.");
    lv_obj_set_style_text_color(ui_auth_test, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_auth_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_auth_test, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_auth_test, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qr1 = lv_image_create(ui_content3);
    lv_image_set_src(ui_qr1, &ui_img_qr_code1_png);
    lv_obj_set_width(ui_qr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_qr1, -30);
    lv_obj_set_y(ui_qr1, 25);
    lv_obj_set_align(ui_qr1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_qr1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_qr1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_card2 = ui_card_create(ui_Step2);
    lv_obj_set_x(ui_card2, -202);
    lv_obj_set_y(ui_card2, -97);

    lv_obj_set_x(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_H), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_H), 74);
    lv_label_set_text(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_H), "Authentication");

    lv_obj_set_x(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT), 180);
    lv_label_set_text(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "The first step is to plug the charger into thecar's charging port.\n");
    lv_obj_add_flag(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT), LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_x(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TITLE), 66);
    lv_obj_set_y(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_label_set_text(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Step");

    ui_step_label2 = lv_label_create(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_step_label2, 51);
    lv_obj_set_height(ui_step_label2, 51);
    lv_obj_set_x(ui_step_label2, 3);
    lv_obj_set_y(ui_step_label2, 0);
    lv_label_set_text(ui_step_label2, "2");
    lv_obj_set_style_text_color(ui_step_label2, lv_color_hex(0x20203A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_step_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_step_label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_step_label2, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_step_label2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_step_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_step_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_step_label2, 3);
    ui_phone = lv_image_create(ui_Step2);
    lv_image_set_src(ui_phone, &ui_img_phone_png);
    lv_obj_set_width(ui_phone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phone, -110);
    lv_obj_set_y(ui_phone, 0);
    lv_obj_set_align(ui_phone, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_phone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_phone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_icon_group5, ui_event_icon_group5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_icon_group6, ui_event_icon_group6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button3, ui_event_button3_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Step2, ui_event_Step2, LV_EVENT_ALL, NULL);

}

void ui_Step2_screen_destroy(void)
{
    if(ui_Step2) lv_obj_del(ui_Step2);

    // NULL screen variables
    ui_Step2 = NULL;
    ui_content_group3 = NULL;
    ui_slidebar3 = NULL;
    ui_icon_group5 = NULL;
    ui_pricing_icon3 = NULL;
    ui_pricing_label3 = NULL;
    ui_icon_group6 = NULL;
    ui_help_icon3 = NULL;
    ui_help_label3 = NULL;
    ui_content3 = NULL;
    ui_info_group3 = NULL;
    ui_contact_icon3 = NULL;
    ui_call_number3 = NULL;
    ui_date2 = NULL;
    ui_button3 = NULL;
    ui_step_count3 = NULL;
    ui_step_count4 = NULL;
    ui_auth_test = NULL;
    ui_qr1 = NULL;
    ui_card2 = NULL;
    ui_step_label2 = NULL;
    ui_phone = NULL;

}
