// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Welcome = NULL;
lv_obj_t * ui_content_group4 = NULL;
lv_obj_t * ui_content4 = NULL;
lv_obj_t * ui_info_group4 = NULL;
lv_obj_t * ui_contact_icon4 = NULL;
lv_obj_t * ui_call_number4 = NULL;
lv_obj_t * ui_date4 = NULL;
lv_obj_t * ui_button4 = NULL;
lv_obj_t * ui_card3 = NULL;
lv_obj_t * ui_welcom_text118 = NULL;
lv_obj_t * ui_fee_group18 = NULL;
lv_obj_t * ui_Label1_fee = NULL;
lv_obj_t * ui_Label3_fee = NULL;
lv_obj_t * ui_fee_group28 = NULL;
lv_obj_t * ui_Label4_fee = NULL;
lv_obj_t * ui_Label5_fee = NULL;
lv_obj_t * ui_ready = NULL;
// event funtions
void ui_event_Welcome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        big_left_on_Animation(ui_card3, 0);
        bottom_on_Animation(ui_button4, 0);
        ready_on_Animation(ui_ready, 300);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_card3, 0);
        bottom_off_Animation(ui_button4, 0);
        ready_off_Animation(ui_ready, 0);
    }
}

void ui_event_button4_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charging, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Charging_screen_init);
    }
}

// build funtions

void ui_Welcome_screen_init(void)
{
    ui_Welcome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Welcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Welcome, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group4 = lv_obj_create(ui_Welcome);
    lv_obj_set_width(ui_content_group4, lv_pct(100));
    lv_obj_set_height(ui_content_group4, lv_pct(100));
    lv_obj_set_align(ui_content_group4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_content_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content4 = lv_obj_create(ui_content_group4);
    lv_obj_set_height(ui_content4, lv_pct(100));
    lv_obj_set_flex_grow(ui_content4, 1);
    lv_obj_set_align(ui_content4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_content4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group4 = lv_obj_create(ui_content4);
    lv_obj_set_width(ui_info_group4, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_info_group4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_info_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon4 = lv_image_create(ui_info_group4);
    lv_image_set_src(ui_contact_icon4, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_contact_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number4 = lv_label_create(ui_info_group4);
    lv_obj_set_width(ui_call_number4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number4, "1-899-547-7878");
    lv_obj_set_style_text_color(ui_call_number4, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number4, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date4 = lv_label_create(ui_content4);
    lv_obj_set_width(ui_date4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date4, 0);
    lv_obj_set_y(ui_date4, 1);
    lv_obj_set_align(ui_date4, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date4, "Jan. 06. 2026. 14:49");
    lv_obj_set_style_text_color(ui_date4, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date4, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button4 = ui_button_create(ui_content4);
    lv_obj_set_x(ui_button4, 0);
    lv_obj_set_y(ui_button4, -8);
    lv_obj_set_align(ui_button4, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button4, UI_COMP_BUTTON_BUTTON_LABEL), "Continue");

    ui_card3 = ui_card_create(ui_Welcome);
    lv_obj_set_width(ui_card3, 706);
    lv_obj_set_height(ui_card3, 600);
    lv_obj_set_x(ui_card3, 0);
    lv_obj_set_y(ui_card3, 0);
    lv_obj_set_align(ui_card3, LV_ALIGN_LEFT_MID);

    lv_obj_set_width(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2), 650);
    lv_obj_set_height(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2), 514);
    lv_obj_set_x(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2), 18);
    lv_obj_set_style_shadow_width(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2), 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_H), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_H), 99);
    lv_label_set_text(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_H), "Authentication");
    lv_obj_add_flag(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_H), LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_x(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_TEXT), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_TEXT), 72);
    lv_label_set_text(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "The first 30 minutes of fast charging are free.\nAfter 60 minutes you get 10% discount.");

    lv_obj_set_x(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_obj_set_y(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_TITLE), 0);
    lv_label_set_text(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Welcome, Jeremy");

    ui_welcom_text118 = lv_label_create(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_welcom_text118, lv_pct(100));
    lv_obj_set_height(ui_welcom_text118, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_welcom_text118, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_welcom_text118, "The charging speed depends on the type of car\nand the capacity of the network.");
    lv_obj_set_style_text_color(ui_welcom_text118, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_welcom_text118, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_welcom_text118, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_welcom_text118, 3);
    ui_fee_group18 = lv_obj_create(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_fee_group18, 460);
    lv_obj_set_height(ui_fee_group18, 130);
    lv_obj_set_x(ui_fee_group18, 0);
    lv_obj_set_y(ui_fee_group18, -50);
    lv_obj_set_align(ui_fee_group18, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_fee_group18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1_fee = lv_label_create(ui_fee_group18);
    lv_obj_set_width(ui_Label1_fee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1_fee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1_fee, 0);
    lv_obj_set_y(ui_Label1_fee, 38);
    lv_label_set_text(ui_Label1_fee, "Session fee");
    lv_obj_set_style_text_color(ui_Label1_fee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1_fee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1_fee, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3_fee = lv_label_create(ui_fee_group18);
    lv_obj_set_width(ui_Label3_fee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3_fee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3_fee, 0);
    lv_obj_set_y(ui_Label3_fee, 7);
    lv_obj_set_align(ui_Label3_fee, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label3_fee, "$0.00");
    lv_obj_set_style_text_color(ui_Label3_fee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3_fee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3_fee, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group18, 4);
    ui_fee_group28 = lv_obj_create(ui_comp_get_child(ui_card3, UI_COMP_CARD_CARDBG2));
    lv_obj_set_height(ui_fee_group28, 130);
    lv_obj_set_width(ui_fee_group28, LV_SIZE_CONTENT);   /// 499
    lv_obj_set_x(ui_fee_group28, 0);
    lv_obj_set_y(ui_fee_group28, 130);
    lv_obj_set_align(ui_fee_group28, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_fee_group28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4_fee = lv_label_create(ui_fee_group28);
    lv_obj_set_width(ui_Label4_fee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4_fee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4_fee, 0);
    lv_obj_set_y(ui_Label4_fee, -3);
    lv_label_set_text(ui_Label4_fee, "1-250 kW charging power will be applied.");
    lv_obj_set_style_text_color(ui_Label4_fee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4_fee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4_fee, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5_fee = lv_label_create(ui_fee_group28);
    lv_obj_set_width(ui_Label5_fee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5_fee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5_fee, 0);
    lv_obj_set_y(ui_Label5_fee, -32);
    lv_obj_set_align(ui_Label5_fee, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label5_fee, "$0.21/kWh");
    lv_obj_set_style_text_color(ui_Label5_fee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5_fee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5_fee, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group28, 5);
    ui_ready = lv_image_create(ui_Welcome);
    lv_image_set_src(ui_ready, &ui_img_ok_png);
    lv_obj_set_width(ui_ready, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ready, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ready, 207);
    lv_obj_set_y(ui_ready, 27);
    lv_obj_set_align(ui_ready, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ready, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ready, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_button4, ui_event_button4_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Welcome, ui_event_Welcome, LV_EVENT_ALL, NULL);

}

void ui_Welcome_screen_destroy(void)
{
    if(ui_Welcome) lv_obj_del(ui_Welcome);

    // NULL screen variables
    ui_Welcome = NULL;
    ui_content_group4 = NULL;
    ui_content4 = NULL;
    ui_info_group4 = NULL;
    ui_contact_icon4 = NULL;
    ui_call_number4 = NULL;
    ui_date4 = NULL;
    ui_button4 = NULL;
    ui_card3 = NULL;
    ui_welcom_text118 = NULL;
    ui_fee_group18 = NULL;
    ui_Label1_fee = NULL;
    ui_Label3_fee = NULL;
    ui_fee_group28 = NULL;
    ui_Label4_fee = NULL;
    ui_Label5_fee = NULL;
    ui_ready = NULL;

}
