// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: EV_Charger

#ifndef UI_WELCOME_H
#define UI_WELCOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Welcome
extern void ui_Welcome_screen_init(void);
extern void ui_Welcome_screen_destroy(void);
extern void ui_event_Welcome(lv_event_t * e);
extern lv_obj_t * ui_Welcome;
extern lv_obj_t * ui_content_group4;
extern lv_obj_t * ui_content4;
extern lv_obj_t * ui_info_group4;
extern lv_obj_t * ui_contact_icon4;
extern lv_obj_t * ui_call_number4;
extern lv_obj_t * ui_date4;
extern void ui_event_button4_button(lv_event_t * e);
extern lv_obj_t * ui_button4;
extern lv_obj_t * ui_card3;
extern lv_obj_t * ui_welcom_text118;
extern lv_obj_t * ui_fee_group18;
extern lv_obj_t * ui_Label1_fee;
extern lv_obj_t * ui_Label3_fee;
extern lv_obj_t * ui_fee_group28;
extern lv_obj_t * ui_Label4_fee;
extern lv_obj_t * ui_Label5_fee;
extern lv_obj_t * ui_ready;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

